import Head from 'next/head'
import styled from 'styled-components';

export const Container = styled.div`
  border: 2px solid red;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Visions of Hope Psychological Services, LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        
      </main>

      
    </div>
  )
}
